### ISSUE TITLE
Clarify applicability of MIT license

### ISSUE THREAD

**Issue by mundschenk-at** [rockettpw/textformatter-typographer#1]
The top-level LICENSE file should make it clear to which parts of the code it applies: 
- The current version of php-typography is licensed under the terms of the GPL2 or a newer version, while the original one by Jeff was GPL2 only. When I started working on wp-Typography, I got permission to relicense everything under the newer scheme to make the plugin "future proof".)
- HTML5-PHP has its own LICENSE file that should be referenced.

**Comment by mikerockett** [comment]
Thanks - so can I just specify that the top-level license applies only to code in the root directory?

**Comment by mundschenk-at** [comment]
Something like that, yes. I'd also list the components in the top-level LICENSE, like HTML5-PHP does in theirs (that reminds me, wp-Typography/php-typography don't have a LICENSE file yet, only https://code.mundschenk.at/wp-typography/license/)

**Comment by mikerockett** [comment]
Okay, I'll do that as soon as you've formulated the license content for php-typography. I'll include the following:

- TextformatterTypographer = MIT
- PHP Typography = GNU GPL2
- HTML5-PHP = MIT (+copyright holders)
- HTML5Lib = MIT (+copyright holders)

**Comment by mikerockett** [comment]
But I'll included the licenses as is instead of referencing them, as you have done.

**Comment by mundschenk-at** [comment]
@mikerockett I've added a LICENSE.md and released wp-Typography 4.0.0.

**Comment by mikerockett** [comment]
Thanks, I have amended the license file. Please let me know if it's satisfactory.

**Comment by mundschenk-at** [comment]
Looks good!
