### ISSUE TITLE
PHP-Typography is now a Composer library

### ISSUE THREAD

**Issue by mundschenk-at** [rockettpw/textformatter-typographer#2]
You can now require the [mundschenk-at/php-typography](https://github.com/mundschenk-at/php-typography) library to include PHP-Typography (beware that the API has changed slightly, there is no default `Settings` object anymore).

**Comment by mikerockett** [comment]
Thanks -- I'll be looking at everything soon. I'll be 'retiring' [Typeset](/mikerockett/php-typeset) in favour of sticking to Typography, instead of introducing another module based on Typeset.

**Comment by mikerockett** [comment]
I've moved over to the Composer package now. Per the readme, further changes will be implemented, but everything seems to run smoothly at this point.

Thanks! 👍
